/* CVS $Id: $ */
package ca.uqam.vocab.dspace; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from /home/heon/01-SPRINT/00-PROJET-DSPACE-VIVO/00-GIT/DSpace-VIVO/bundles/ca.uqam.dspace2vivo.model.ontologie/src/main/resources/dspace.ttl 
 * @author Auto-generated by schemagen on 22 mars 2022 04:27 
 */
public class DSPACE {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://vivoweb.org/ontology/dspace#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Created with TopBraid Composer";
    
    public static final OntClass Collection = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Collection" );
    
    public static final OntClass Community = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Community" );
    
    public static final OntClass Item = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Item" );
    
    public static final OntClass Repository = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Repository" );
    
}
